#!/bin/bash
set -e -u -o pipefail


#git diff-index --quiet HEAD -- \
#|| (echo "Working tree is dirty. Commit all changes."; false)

ENV="$1"
if [ ! -d terraform/env/$ENV/ ]; then
  echo missing: terraform/env/$ENV/ >&2
  exit 1
fi
GITSHA=$(git rev-parse HEAD)
TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M:%S +0000 UTC')"


function build-and-push() {
    declare FN="$1"
    declare REPO="$2"

    echo "Preparing ${FN}..."
    declare NAME=$(echo $REPO | sed 's|.*/||')
    declare TAG=${REPO}:${GITSHA}

    echo "Building ${FN}..."
    docker build \
        --build-arg=GITSHA="$GITSHA" \
        --build-arg=TIMESTAMP="$TIMESTAMP" \
        --compress --force-rm --pull \
        -t $TAG \
        -f ./docker/${FN}/Dockerfile \
        .

    echo "Pushing ${FN}..."
    docker push $TAG

    echo "Tagging latest..."
    docker tag $TAG ${REPO}:latest
    aws ecr batch-delete-image \
        --repository-name $NAME \
        --image-ids imageTag=latest
    docker push ${REPO}:latest
}


for FN in rekey-fn web-fn; do
    REPO=$(scripts/get-repo-url $ENV $FN)
    build-and-push $FN $REPO
    ${AWSCLI:-aws} lambda update-function-code \
        --function-name $(scripts/get-fn-name $ENV $FN) \
        --image-uri "$REPO":latest
done
